import type { Metadata } from "next";
import { Yusei_Magic } from "next/font/google";
import "./globals.css";

const yuseiMagic = Yusei_Magic({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "りゆうの実験場",
  description: "Generated by create next app だよ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={yuseiMagic.className}>{children}</body>
    </html>
  );
}
